 - name: K8S-PalyBook
   hosts: web
   gather_facts: false 
   vars_files:
    - ./vars.yaml
   vars:
    path: "/deployments"
    # copy files 
    files:
    - nginx-deployment.yaml
    - mykey.pem
    # - service.yaml 
   tasks:
    
    - name: Make Dir
      ansible.builtin.file:
        path: /deployments
        state: directory
        owner: ubuntu
        group: ubuntu 

    - name: CP K8s Yamls
      copy:
       src: "{{item}}"
       dest: "{{ path  }}"
      loop: "{{files}}"
    
    - name: cp service with subnets
      template:
       src: service.yaml.j2
       dest: "{{ path  }}/service.yaml"

    - name: chmod ssh key
      command: "chmod 400 /deployments/mykey.pem"